name: Publish Python Package

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Set Build Variables
      run: |
        if [[ "$GITHUB_REF" =~ ^refs/tags/v* ]]; then
          echo "Using TAG mode: $GITHUB_REF_NAME"
          echo "PKG_VERSION=$GITHUB_REF_NAME" >> $GITHUB_ENV
          echo "PKG_VERSION_STRICT=${GITHUB_REF_NAME#?}" >> $GITHUB_ENV
          echo "TWINE_REPOSITORY_URL=https://test.pypi.org/legacy/" >> $GITHUB_ENV
        else
          echo "Using BRANCH mode: v2.0.0-dev.$GITHUB_RUN_NUMBER"
          echo "PKG_VERSION=v2.0.0-dev.$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
          echo "PKG_VERSION_STRICT=2.0.0-dev.$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
          echo "TWINE_REPOSITORY_URL=https://test.pypi.org/legacy/" >> $GITHUB_ENV
        fi
    
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Install Python dependencies
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        python -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip setuptools wheel twine
        pip install build
        sudo apt update
        sudo apt install -y twine
        
    - name: Build Python package
      run: |
        echo "Using version $PKG_VERSION_STRICT"
        sed -i -r -e "s/^__version__ = '.*'$/__version__ = '$PKG_VERSION_STRICT'/" rfc2html.py
        python ./setup.py setopt --command=metadata --option=version --set-value=$PKG_VERSION_STRICT
        python ./setup.py sdist --dist-dir dist
        
    - name: Import Test GPG Key
      uses: crazy-max/ghaction-import-gpg@cb4264d3319acaa2bea23d51ef67f80b4f775013
      if: startsWith(github.ref, 'refs/tags/v') != true
      with:
        gpg_private_key: ${{ secrets.TEST_GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.TEST_GPG_PASSPHRASE }}
        
    - name: Import GPG Key
      uses: crazy-max/ghaction-import-gpg@cb4264d3319acaa2bea23d51ef67f80b4f775013
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.GPG_PASSPHRASE }}
        
    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_TOKEN }}
      run: |
        echo "Using repository $TWINE_REPOSITORY_URL"
        twine check dist/*
        twine upload --verbose --sign dist/*
        
    - name: Fetch Changelog Config
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        wget https://github.com/ietf-tools/common/raw/main/ci-configs/tag-changelog-config.js
        
    - name: Create Changelog
      id: changelog
      uses: loopwerk/tag-changelog@v1
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        config_file: tag-changelog-config.js
        
#     - name: Update CHANGELOG.md
#       uses: vemel/nextchange@0.1.1
#       if: startsWith(github.ref, 'refs/tags/v')
#       with:
#         release: ${{ env.PKG_VERSION }}
#         clear: true
#         set: ${{ steps.changelog.outputs.changes }}
#         save: true
        
#     - name: Update CHANGELOG.md
#       uses: stefanzweifel/changelog-updater-action@v1
#       if: startsWith(github.ref, 'refs/tags/v')
#       with:
#         latest-version: ${{ env.PKG_VERSION_STRICT }}
#         release-notes: ${{ steps.changelog.outputs.changes }}

    - name: Commit CHANGELOG.md
      uses: stefanzweifel/git-auto-commit-action@v4
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        branch: main
        commit_message: 'docs: update CHANGELOG.md for ${{ github.ref_name }} [skip ci]'
        file_pattern: CHANGELOG.md
        
    - name: Create Release
      uses: ncipollo/release-action@v1
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        allowUpdates: true
        draft: false
        name: ${{ github.ref_name }}
        body: ${{ steps.changelog.outputs.changes }}
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v2.3.1
      with:
        name: artifacts
        path: |
          CHANGELOG.md
          rfc2html.py
          setup.cfg
