on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel twine
        pip install build
        
    - name: Build Python package
      run: |
        sed -i -r -e "s/^__version__ = '.*'$/__version__ = '2.0.${{ github.run_number }}'/" rfc2html.py
        sed -i -r -e "s/^version = .*$/2.0.${{ github.run_number }}/" setup.cfg
        python -m build
        
    - name: Publish to Test PyPI
      uses: pypa/gh-action-pypi-publish@v1.5.0
      with:
        password: ${{ secrets.TEST_PYPI_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
        verbose: true
        print_hash: true
